# Generated by Django 2.2.24 on 2021-11-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='products',
            field=models.IntegerField(),
        ),
    ]
