# Generated by Django 2.2.24 on 2021-12-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211202_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bike',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.Bike'),
        ),
    ]
